
# Loads default set of integrations. Do not remove.
default_config:

# Cloudflare allow reversed proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Roborock Garage control
rest_command:
  roborock_open:
    url: !secret roborock_nodemcu_url
    method: POST
    content_type: "application/x-www-form-urlencoded"
    payload: "value=135"
  roborock_close:
    url: !secret roborock_nodemcu_url
    method: POST
    content_type: "application/x-www-form-urlencoded"
    payload: "value=0"

# Google assistant
google_assistant:
  project_id: !secret google_project_id
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - light
    - group
    - scene
    - media_player

# Alpha Innotec warmtepomp integratie
luxtronik:
  host: !secret luxtronik_ip
  port: !secret luxtronik_port
  
# Custom Sensors
sensor:

    # Alpha Innotec warmtepomp
  - platform: luxtronik
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TA
        friendly_name: Luxtronik Temperatuur buiten

      - group: calculations
        id: ID_WEB_RBE_RT_Ist
        friendly_name: Luxtronik Ruimte temperatuur nu

      - group: calculations
        id: ID_WEB_WP_BZ_akt
        friendly_name: Luxtronik Toestand  

# iPad dashboard sidebar
template: !include sidebar.yaml

# iPad dashboard
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Tablet
      icon: mdi:tablet
      show_in_sidebar: true
      filename: ui-lovelace.yaml
