# Enable Kiosk mode for user tablet
kiosk_mode:
  user_settings:
    - users:
        - "maurice"
        - "tablet"
      hide_header: true

button_card_templates:
  !include_dir_merge_named button_card_templates

views:
  - type: custom:grid-layout
    background: center / cover no-repeat fixed url('/local/background.png')
    title: Home
    layout:
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .        .        .          ."
        "sidebar  floor    floor    calendar   ."
        "sidebar  floor    floor    calendar   ."
        "sidebar  footer   footer   footer     ."
    cards:

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar
