# Enable Kiosk mode for user tablet
kiosk_mode:
  user_settings:
    - users:
        - "tablet"
      hide_header: true

views:
  - type: custom:grid-layout
    title: Home
    layout:
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .        .        .          ."
        "sidebar  floor    floor    calendar   ."
        "sidebar  floor    floor    calendar   ."
        "sidebar  footer   footer   footer     ."
